PROJECT = ifj17

CC = gcc
RM = rm -rf

STD_C99 = -std=c99
CFLAGS = -Wall -Wextra -pedantic 

all:
	$(CC) $(STD_C99) $(CFLAGS) abstract_tree.c gen_stacks.c stack.c string_storage.c set_values.c at_que.c generator.c destructor.c frame.c lexical.c error.c symtable.c precedence_sa.c token.c parser.c  main.c -o main